module.exports={
    ADMIN_COLLECTION:'adminCollection',
    STUDENTS_COLLECTION:'studentCollection',
    ASSIGNMENTS_COLLECTION:'assignmentsCollection',
    NOTES_COLLECTION:'notesCollection',
    PHOTOS_COLLECTIONS:'photoCollection',
    ANNOUNCEMENTS_COLLECTIONS:'announcementCollection',
    EVENTS_COLLECTIONS:'eventCollection',
    FEE_COLLECTIONS:'feecollecction'
}
